The-Strategy-Unit/nhp_project_information

project_plan_and_summary/model_updates.qmd
=> added update listing open source repositories

_quarto.yml, contact.qmd, modelling_methodology/baseline_data_validation.qmd
=> added contact page

project_plan_and_summary/model_updates.qmd
Closes #16.
Added bullets about the changes to the inputs and outputs apps, which are both moving to v1.1.1.
Not sure why the whole file says it's changed. Only lines 21 to 36 were inserted.
=> Notes on v1.1.1

.github/workflows/connect-publish-dev.yaml, _publish.yml
Updating the GUID for the dev deployment due to redeployment on Posit Connect
=> Update dev deploy GUID

_quarto.yml
=> amended quarto yaml - contact link from sidebar now works

.github/ISSUE_TEMPLATE/release-checklist.md
=> Create issue template for release checklist

user_guide/FAQ.qmd
Adding responses to the FAQ for a couple of queries we've had. Fixes #50
=> Add outpatient DNA & monthly inpatient questions to FAQ

user_guide/mitigators_lookup.qmd
=> 56 number of mitigators

user_guide/glossary.qmd
=> updated waterfall explanation with worked example

project_plan_and_summary/model_updates.qmd, user_guide/glossary.qmd
incorporating @jakep03 suggestions via email
=> Update to numbers in model interaction term explanation

user_guide/naming_scenarios.qmd, user_guide/setting_the_parameters.qmd
=> added model naming guidance

data_extraction/inpatients.qmd
=> added link to data log and additional info on well babies

user_guide/glossary.qmd
Closes #72 
Still waiting for final confirmation on terminology around confidence intervals in results vs in model params, due 9th August
=> added confidence intervals to glossary

user_guide/setting_the_parameters.qmd
=> removed reference to old principal from time profiles description

.github/ISSUE_TEMPLATE/release-checklist.md
will remove when app for moving scenarios has been launched
closes #73
=> added nhp_admin_model_run to QA checklist

user_guide/results.qmd
=> updated age groups in parsing model results page

project_plan_and_summary/model_updates.qmd
Note that data log has not been updated yet!
closes #83
=> model update for 2.1

data_extraction/data_log.qmd, data_extraction/inpatients.qmd
Need help on the section on "last episode in spell". it will also need to be updated in `data_extraction/inpatients.qmd`
closes #80
=> first draft of data log update

user_guide/glossary.qmd
Fixes #70
I've attempted to merge a simple explanation with the more complex mathematical one already there. Aware that I may have done this imperfectly and very happy for PR to be changed/ discussed accordingly
=> Lay description of model interaction term

project_plan_and_summary/model_updates.qmd
Requesting review from everyone under the sun because I know Chris is busy today and may not have time to approve
=> added process for upgrading to 2.1

data_extraction/inpatients.qmd
=> updated IP tretspef mappings

_quarto.yml
=> Add edit and issue buttons

quality_assurance/assumptions.json
Fixes paths in the assumption log links. Closes #128
=> :bug: Fix URLs in assumptions log

modelling_methodology/covid_adjustment.qmd
=> ✏️ Fix LaTeX formatting

project_plan_and_summary/model_updates.qmd
=> 🔊 Add model updates v3.0

data_extraction/data_log.qmd
I've made a start on the data log
=> 📝 Update data log

user_guide/results.qmd
=> Update LoS categories

project_plan_and_summary/model_updates.qmd
=> Model update info for v3.0.1

user_guide/glossary.qmd
=> add time profiles explanation

_quarto.yml, data_extraction/data_log.qmd, index.qmd, modelling_methodology/ndg2_analysis.html, modelling_methodology/ndg_analysis.html, nhp_project_information.Rproj, project_plan_and_summary/model_updates.qmd, user_guide/glossary.qmd, user_guide/non-demographic_growth.html
=> Adds update for v3.1

modelling_methodology/activity_mitigators/inpatient_activity_mitigators.qmd
Closes https://github.com/The-Strategy-Unit/nhp_data/issues/9
=> Added clarification for IP-AA-028

modelling_methodology/demographic_modelling/demographic_modelling.qmd
=> added more detail on demographic growth method

data_extraction/data_log.qmd, project_plan_and_summary/model_updates.qmd, user_guide/FAQ.qmd
=> v3.2 update

user_guide/glossary.qmd
Strengthened the wording, and added corrected worked example with expandable R code to reproduce locally.
=> Glossary ci example

data_extraction/data_log.qmd, data_extraction/outpatients.qmd, modelling_methodology/baseline_data_validation.qmd, project_plan_and_summary/model_updates.qmd
Should I provide more detail on NDG?
Closes #193 
Closes #188 
Contributes to #https://github.com/The-Strategy-Unit/nhp_planning/issues/207
=> 3.3 update

.github/workflows/connect-publish-dev.yaml, .github/workflows/connect-publish-pr.yaml, .github/workflows/connect-publish-prod.yaml
Related to https://github.com/The-Strategy-Unit/nhp_planning/issues/213
=> workflow publishes to new connect server

project_plan_and_summary/components-overview.qmd, project_plan_and_summary/model_updates.qmd
Altered text in the project_plan_and_summary/components_overview and model_updates sections to reflect new open status. Date of update set to today, even though opening was on March 11th I think.
=> Add a new open code update and text

modelling_methodology/modelling_uncertainty.qmd, user_guide/FAQ.qmd
=> Wording to describe the effect of the methodology change agreed by KB

data_extraction/data_log.qmd, modelling_methodology/activity_mitigators/inpatient_activity_mitigators.qmd, modelling_methodology/demographic_modelling/demographic_modelling.qmd, project_plan_and_summary/model_updates.qmd, user_guide/setting_the_parameters.qmd
Closes #207 
Closes #205 
Contributes to https://github.com/The-Strategy-Unit/nhp_planning/issues/266
=> Updates for model v3.4

project_plan_and_summary/model_updates.qmd
=> Open source message with links to SU policy and blog

data_extraction/data_log.qmd, project_plan_and_summary/model_updates.qmd
This is a very minimal update! Most of the changes are more of interest to developers - I don't think it important to share the JSON schema news, for example.
Am I missing anything @matt-dray ? I know there were lots of small PRs in inputs/outputs but not sure if worth mentioning in model update.
=> add model update v3.5

data_extraction/data_log.qmd, project_plan_and_summary/model_updates.qmd
@ChrisBeeley  do you want to work on this branch and add your text to `model_updates.qmd`? or you can supply text to me and I will add it in
=> added updates for v3.6

data_extraction/aae.qmd, quality_assurance/assumptions.json
=> Add ECDS to assumption log and mention on AAE page

modelling_methodology/demographic_modelling/demographic_modelling.qmd
=> Update demog growth catchment text

data_extraction/data_log.qmd
=> Update data log for v4.2
